version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: insurance_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: insurance_db
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - insurance_network

  app:
    build: .
    container_name: insurance_app
    restart: always
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/insurance_db?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - insurance_network
    command: sh -c "npm install && npm start"

volumes:
  mongodb_data:

networks:
  insurance_network:
    driver: bridge 