name: Claude Code – Opus 4

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      # ⬇️ צעד חדש – תמיד משדרג ל-latest (יותר מ-1.0.24)
      - name: Update Claude CLI
        run: npm install -g @anthropic-ai/claude-code@latest

         # האקשן הראשי – עדכן רק את המספר
      - uses: anthropics/claude-code-action@v0.0.24   # ← במקום v0.0.18
        with:
          github_token:      ${{ secrets.GH_PAT }}
          model:             claude-opus-4-20250514
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

