name: Claude Code – Opus 4

on:
  issue_comment:               # … בלי שינוי …
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - uses: anthropics/claude-code-action@v0.0.18
        with:                                   # ⬅️ כאן!
          github_token:        ${{ secrets.GH_PAT }}
          model:               claude-opus-4-20250514
          anthropic_api_key:   ${{ secrets.ANTHROPIC_API_KEY }}   # ← המפתח
